// internal/config/gencfg.go
package config

import (
	"encoding"
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// RenderDocumented generates a documented TOML config from cfg: `doc:"..."`
// tags become `# ` comments, `toml:"..."` tags become keys, values come from
// cfg (ExampleConfig() is the curated source of truth). Schema + comments are
// reflected from the structs, so they can never drift from the code.
func RenderDocumented(cfg AppConfig) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `ringer gen-config`.\n")
	b.WriteString("# Schema + docs come from the config structs (internal/config); copy to your\n")
	b.WriteString("# config path (default ~/.config/ringer/config.toml, override with --config).\n\n")
	if err := writeSections(&b, reflect.TypeOf(cfg), reflect.ValueOf(cfg), "", ""); err != nil {
		return "", err
	}
	return b.String(), nil
}

// writeSections walks a struct two-pass — TOML requires bare keys before any
// [table], so leaves are emitted first, then struct / map[string]struct
// sections as [path] / [path.<key>] tables (map keys sorted).
func writeSections(b *strings.Builder, t reflect.Type, v reflect.Value, path, sectionDoc string) error {
	if sectionDoc != "" {
		writeCommentBlock(b, sectionDoc)
	}
	if path != "" {
		fmt.Fprintf(b, "[%s]\n", path)
	}
	for i := 0; i < t.NumField(); i++ { // pass 1: leaves
		f := t.Field(i)
		name := tomlName(f)
		if !f.IsExported() || name == "" || isSection(f.Type) {
			continue
		}
		lit, err := tomlLiteral(v.Field(i))
		if err != nil {
			return fmt.Errorf("field %s: %w", f.Name, err)
		}
		if doc := f.Tag.Get("doc"); doc != "" {
			writeCommentBlock(b, doc)
		}
		fmt.Fprintf(b, "%s = %s\n", name, lit)
	}
	for i := 0; i < t.NumField(); i++ { // pass 2: sections
		f := t.Field(i)
		name := tomlName(f)
		if !f.IsExported() || name == "" || !isSection(f.Type) {
			continue
		}
		child := name
		if path != "" {
			child = path + "." + name
		}
		fv := v.Field(i)
		if f.Type.Kind() == reflect.Map {
			keys := fv.MapKeys()
			sort.Slice(keys, func(a, c int) bool { return keys[a].String() < keys[c].String() })
			for _, k := range keys {
				b.WriteString("\n")
				ev := fv.MapIndex(k)
				if err := writeSections(b, ev.Type(), ev, child+"."+k.String(), f.Tag.Get("doc")); err != nil {
					return err
				}
			}
			continue
		}
		b.WriteString("\n")
		if err := writeSections(b, f.Type, fv, child, f.Tag.Get("doc")); err != nil {
			return err
		}
	}
	return nil
}

// isSection reports whether a field renders as a [table]: a struct, or a map
// whose element is a struct.
func isSection(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Struct:
		return true
	case reflect.Map:
		return t.Elem().Kind() == reflect.Struct
	}
	return false
}

func writeCommentBlock(b *strings.Builder, doc string) {
	for _, line := range strings.Split(doc, "\n") {
		fmt.Fprintf(b, "# %s\n", strings.TrimRight(line, " "))
	}
}

func tomlName(f reflect.StructField) string {
	name, _, _ := strings.Cut(f.Tag.Get("toml"), ",")
	if name == "-" {
		return ""
	}
	if name == "" {
		return f.Name
	}
	return name
}

// tomlLiteral renders a scalar/slice/pointer/TextMarshaler value as a TOML
// literal. Order matters: pointer-deref and TextMarshaler/Stringer run BEFORE
// the integer branch, so slog.Level renders as "INFO" (via its Stringer/
// TextMarshaler), never as its int value 0 (which would fail UnmarshalText).
func tomlLiteral(v reflect.Value) (string, error) {
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return tomlLiteral(reflect.Zero(v.Type().Elem()))
		}
		return tomlLiteral(v.Elem())
	}
	if v.CanInterface() {
		switch m := v.Interface().(type) {
		case encoding.TextMarshaler:
			txt, err := m.MarshalText()
			if err != nil {
				return "", err
			}
			return strconv.Quote(string(txt)), nil
		case fmt.Stringer:
			return strconv.Quote(m.String()), nil
		}
	}
	switch v.Kind() {
	case reflect.String:
		return strconv.Quote(v.String()), nil
	case reflect.Bool:
		return strconv.FormatBool(v.Bool()), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return strconv.FormatInt(v.Int(), 10), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return strconv.FormatUint(v.Uint(), 10), nil
	case reflect.Float32, reflect.Float64:
		return strconv.FormatFloat(v.Float(), 'g', -1, 64), nil
	case reflect.Slice, reflect.Array:
		parts := make([]string, v.Len())
		for i := 0; i < v.Len(); i++ {
			p, err := tomlLiteral(v.Index(i))
			if err != nil {
				return "", err
			}
			parts[i] = p
		}
		return "[" + strings.Join(parts, ", ") + "]", nil
	}
	return "", fmt.Errorf("gen-config: unsupported kind %s", v.Kind())
}
